### ISSUE TITLE
Changing the port in which cermine is  running

### ISSUE THREAD

**Issue by Abhijit-2592** [elifesciences/cermine-docker#4]
Hey how do I change the default port from 8080? I need this functionality because I have another server inside another docker container running in 8080. I need to change cermine's default port from 8080. 

Note:
Am not asking about port mapping in docker.

**Comment by de-code** [comment]
This repo is only packaging CERMINE up as a Docker container.
If you are not asking about Docker port mapping then this is probably a question for the [main CERMINE repo](https://github.com/CeON/CERMINE)?

**Comment by Abhijit-2592** [comment]
Guess you are right
